<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-F8VVTHA" failures="1" tests="3" name="Test" time="30.923" errors="0" timestamp="2022-07-27T12:55:04 IST">
  <testcase classname="testClasses.VerifyUserCanLogin" name="verifyUserCanLogin" time="5.232"/>
  <testcase classname="testClasses.VerifyUserCanAddNewAddress" name="VerifyUserCanGoToProfilePage" time="2.013"/>
  <testcase classname="testClasses.VerifyUserCanAddNewAddress" name="VerifyUserCanAddAddress" time="4.003">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]
at testClasses.VerifyUserCanAddNewAddress.VerifyUserCanAddAddress(VerifyUserCanAddNewAddress.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- VerifyUserCanAddAddress -->
</testsuite> <!-- Test -->
